baseurl: "http://www.rioxx.net"
languageCode: "en-gb"
theme: "rioxx"
enableRobotsTXT: true
title: "RIOXX"
author: "Paul Walk"
copyright: "Copyright © Paul Walk. This website and blog are licensed under a <a rel='license' href='http://creativecommons.org/licenses/by-sa/3.0/deed.en_GB'>Creative Commons Attribution-ShareAlike 3.0 Unported License</a>"
disqusShortname: "rioxx"
metaDataFormat: "yaml"
# rssURI: "feed.xml"
# publishdir: "/Users/paulwalk/_temp/hugo_public/www.rioxx.net"
permalinks:
  post: "/:year/:month/:day/:title/"
  page: "/:title/"
taxonomies:
  tag: "tags"
  topic: "topics"
  category: "categories"
pygmentsCodeFences: true
params:
  tagline: "the RIOXX metadata application profile and guidelines"
  pageSize: "10"
  AuthorName: "Paul Walk"
  showPageStatusTagsOnLiveSite: true
blackfriday:
  smartypants: false
  # hardLineBreak: true
disablePathToLower: false
uglyURLs: false